version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: compliance-postgres
    environment:
      POSTGRES_DB: compliance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sujan
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: compliance-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: compliance-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
